-- 베이스라인 스키마.
-- 기존에 spring.jpa.hibernate.ddl-auto=update 로 만들어져 있던 스키마와 동일하며,
-- 이미 운영/개발 DB가 있는 경우 flyway.baseline-on-migrate 에 의해 건너뛴다.

CREATE TABLE users
(
    id                bigint       GENERATED BY DEFAULT AS IDENTITY,
    email             varchar(255) NOT NULL,
    password          varchar(255) NOT NULL,
    nickname          varchar(255) NOT NULL,
    role              varchar(255) NOT NULL,
    profile_image_url varchar(255),
    last_login_at     timestamp(6),
    created_at        timestamp(6),
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE collections
(
    id         uuid         NOT NULL,
    kind       varchar(255) NOT NULL,
    name       text,
    color      varchar(255),
    icon       varchar(255),
    attributes jsonb        NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    deleted_at timestamp(6),
    CONSTRAINT collections_pkey PRIMARY KEY (id),
    CONSTRAINT collections_kind_check CHECK (kind IN ('CALENDAR', 'NOTEBOOK', 'SEMESTER'))
);

CREATE TABLE collection_users
(
    id            uuid         NOT NULL,
    collection_id uuid         NOT NULL,
    user_id       bigint       NOT NULL,
    role          varchar(255) NOT NULL,
    created_at    timestamp(6),
    CONSTRAINT collection_users_pkey PRIMARY KEY (id),
    CONSTRAINT collection_users_role_check CHECK (role IN ('OWNER', 'EDITOR', 'VIEWER'))
);

CREATE TABLE items
(
    id            uuid   NOT NULL,
    name          text,
    owner_id      bigint NOT NULL,
    collection_id uuid,
    block_codes   jsonb,
    attributes    jsonb  NOT NULL,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted_at    timestamp(6),
    CONSTRAINT items_pkey PRIMARY KEY (id)
);

CREATE TABLE actions
(
    id          uuid    NOT NULL,
    owner_id    bigint  NOT NULL,
    name        text    NOT NULL,
    description text,
    enabled     boolean NOT NULL,
    is_preset   boolean NOT NULL,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted_at  timestamp(6),
    CONSTRAINT actions_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_actions_owner_id ON actions (owner_id);
CREATE INDEX idx_actions_is_preset ON actions (is_preset);

CREATE TABLE action_steps
(
    id            uuid        NOT NULL,
    action_id     uuid        NOT NULL,
    block_code    varchar(40) NOT NULL,
    display_order integer     NOT NULL,
    CONSTRAINT action_steps_pkey PRIMARY KEY (id),
    CONSTRAINT fk_action_steps_action FOREIGN KEY (action_id) REFERENCES actions (id),
    CONSTRAINT uk_action_steps_action_block UNIQUE (action_id, block_code),
    -- 블록 재정렬 중에는 순서가 일시적으로 충돌하므로 제약 검사를 커밋 시점까지 미룬다.
    CONSTRAINT uk_action_steps_action_display_order UNIQUE (action_id, display_order)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT action_steps_block_code_check
        CHECK (block_code IN ('TODO', 'SCHEDULE', 'MEMO', 'TIMETABLE'))
);

CREATE INDEX idx_action_steps_action ON action_steps (action_id, display_order);

CREATE TABLE debug_test
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    message    varchar(255),
    created_at timestamp(6),
    CONSTRAINT debug_test_pkey PRIMARY KEY (id)
);
